# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  coverage-badge:
    name: Generate Jest coverage report badges
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Necessary to push the generated badges to the repo
      - name: Check out repository code
        uses: actions/checkout@v3
      # Necessary to generate the coverage report.
      # Make sure to add 'json-summary' to the coverageReporters in jest options
      - run: npm ci
      - name: Tests
        run: npm test
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest

  publish-npm:
    name: Build and Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
