# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Execute tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test

  coverage-badge:
    name: Generate Jest coverage report badges
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Necessary to push the generated badges to the repo
      - name: Check out repository code
        uses: actions/checkout@v3
      # Necessary to generate the coverage report.
      # Make sure to add 'json-summary' to the coverageReporters in jest options
      - run: npm install
      - name: Coverage
        run: npm run coverage
      - name: Delete badges branch
        run: |-
          git branch -d badges
          git push origin --delete remoteBranchName
      - name: Create badges branch
        run: |-
          git checkout -b badges
          git push --set-upstream origin badges
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest

  publish-npm:
    name: Build and Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
